# Generated by Django 5.1.2 on 2024-10-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
    ]
